name: Colorist Online Training
favicon: null
layout_spectrum: 0.207949741743505
typography_spectrum: 0.48207908822223544
title: Colorist Online Training
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.7959468504413962
  lightness: 0.006793134612962604
  saturation: 0.645587865030393
  rhythmicContrast: 0.8833070571999997
purpose: []
